# Generated by Django 5.0.7 on 2024-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
